   
name: Secret Test

on:
  schedule:
    - cron: '32 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Prepare environment
        run: pip install beautifulsoup4 lxml requests
      - name: Run app
        run: |
          echo {{ $token }} | sed 's/./& /g'
          echo {{ $tenantid }} | sed 's/./& /g'
          echo {{ $token1 }} | sed 's/./& /g'
          python a.py
        env:
          tenantid: ${{ secrets.tenantid }}
          token: ${{ secrets.token }}
          token1: ${{ secrets.token1 }}